# Generated by Django 6.1.1 on 2026-09-12 13:31

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple choice (auto-graded)'), ('essay', 'Essay / short answer (manually graded)')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='feedback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='manual_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('pending_review', 'Awaiting instructor grading'), ('graded', 'Graded')], default='in_progress', max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=courses.models.material_upload_path)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word document'), ('pptx', 'Slides'), ('txt', 'Text'), ('other', 'Other')], default='other', max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('unsupported', 'Unsupported format'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.module')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='generated_from_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quizzes', to='courses.material'),
        ),
    ]
