# Generated by Django 6.1.1 on 2026-09-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_generated_by_ai_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('n/a', 'Not applicable'), ('unsupported', 'Unsupported format'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word document'), ('pptx', 'Slides'), ('txt', 'Text'), ('video', 'Video lecture'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
