# Generated by Django 6.1.1 on 2026-09-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_material_extraction_status_alter_material_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
